name: Run Cargo audit

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 1' # Run on Mondays
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Audit dependencies
        run: cargo audit
