name: Ubuntu build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - '*/*'
      - 'update_flake_lock_action'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        flags:
          - "--cfg async_executor_impl=\"async-std\" --cfg async_channel_impl=\"async-std\""
          - "--cfg async_executor_impl=\"async-std\" --cfg async_channel_impl=\"flume\""
          - "--cfg async_executor_impl=\"tokio\" --cfg async_channel_impl=\"tokio\""
          - "--cfg async_executor_impl=\"tokio\" --cfg async_channel_impl=\"flume\""
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Format
        run: |
          cargo fmt -- --check

      - name: Build
        run: |
          RUSTFLAGS="${{ matrix.flags }}" cargo build --all-targets --workspace --features logging-utils --release

      - name: Test
        run: |
          RUSTFLAGS="${{ matrix.flags }}" cargo test --all-targets --workspace --features logging-utils --release

      - name: Lint
        run: |
          RUSTFLAGS="${{ matrix.flags }}" cargo clippy --workspace --all-targets --features logging-utils --bins --tests --examples -- -D warnings
